export const CURRENCY_EXCHANGE_TRIGGERED = Symbol('CURRENCY_EXCHANGE_TRIGGERED');
export const CURRENCY_EXCHANGE_REQUEST = Symbol('CURRENCY_EXCHANGE_REQUEST');
export const CURRENCY_EXCHANGE_SUCCESS = Symbol('CURRENCY_EXCHANGE_SUCCESS');
export const CURRENCY_EXCHANGE_FAILURE = Symbol('CURRENCY_EXCHANGE_FAILURE');

export const SELECT_CURRENCY = Symbol('SELECT_CURRENCY');
export const SELECT_CRYPTO = Symbol('SELECT_CRYPTO');
